In [6]:



import pandas as pd
import numpy as np
df = pd.read_csv('credit_card.csv')
df.head()

,gender,age,job,marital,education,default,housing,loan,contact,CreditCard
0,female,56,housemaid,married,basic.4y,no,no,no,telephone,no
1,male,57,services,married,high.school,yes,no,no,telephone,no
2,female,37,services,married,high.school,no,yes,no,telephone,no
3,female,40,admin.,married,basic.6y,no,no,no,telephone,no
4,female,56,services,married,high.school,no,no,yes,telephone,no

In [7]:
df.shape

(41188, 10)

In [8]:
df.describe(include='O')

,gender,job,marital,education,default,housing,loan,contact,CreditCard
count,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,2,12,4,8,2,2,2,2,2
top,female,admin.,married,university.degree,no,yes,no,cellular,no
freq,20798,10422,24928,12168,32588,22566,33950,26144,36548

In [9]:
df.describe()

               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000

In [10]:
S = df.shape[0]
print(f"Total number of customers: {S}")

Total number of customers: 41188

In [11]:
has_credit = df[df['CreditCard']!= 'no']
nc = len(has_credit)
print(f"Total Number of customers who do have credit card is {nc}")

Total Number of customers who do have credit card is 4640

In [12]:
p_nc = round(nc/S, 3)
print(f"Probability that a customer do  have a credit card is {p_nc}")

Probability that a customer do  have a credit card is 0.113

In [14]:
old = df[df['age']>50]
old_no = len(old)
print(f"Total Number of customers whose  age is greater than 50 is {old_no}")

Total Number of customers whose  age is greater than 50 is 7180

In [15]:
p_old_no = round(old_no/S,3) 
print(f"Probability that the customer age is greater than 50 is {p_old_no}")

Probability that the customer age is greater than 50 is 0.174

In [16]:
df['education'].value_counts()

education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

In [17]:
hs = 9515
p = hs/S
print(f"Probability that a  Customer is illiterate {round(p, 2)}")

Probability that a  Customer is illiterate 0.23

In [22]:
has_tele = df[df['contact']== 'telephone']
nc = len(has_tele)
print(f"Total Number of customers who  has a Telephone  {nc}")
p_nc = round(nc/S, 3)
print(f"Probability that a customer who  has a Telephone is {p_nc}")

Total Number of customers who  has a Telephone  15044
Probability that a customer who  has a Telephone is 0.365

In [26]:
pd.crosstab(df['marital'],df['CreditCard'],margins=True)

CreditCard     no   yes    All
marital
divorced     4136   476   4612
married     22396  2532  24928
single       9948  1620  11568
unknown        68    12     80
All         36548  4640  41188

In [27]:
c = 22396
print(f"Probability that  a customer is single and having a credit card is {round(c/S, 2)}")

Probability that  a customer is single and having a credit card is 0.54

In [28]:
#. What is the Probability that the Customer is Male and has at most 6 Year of Education ?
pd.crosstab(df['gender'],df['education'],margins=True)

education,basic.4y,basic.6y,basic.9y,high.school,illiterate,professional.course,university.degree,unknown,All
gender,,,,,,,,,
female,2104,1169,3092,4735,7,2647,6142,902,20798
male,2072,1123,2953,4780,11,2596,6026,829,20390
All,4176,2292,6045,9515,18,5243,12168,1731,41188

In [30]:
hs = 1123	
p = hs/S
print(f" Probability that the Customer is Male and has at most 6 Year of Education {round(p, 2)}")

 Probability that the Customer is Male and has at most 6 Year of Education 0.03

In [31]:
# What is the Probability that the Customer is Retired and is divorced 
pd.crosstab(df['marital'],df['job'],margins=True)

job,admin.,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,technician,unemployed,unknown,All
marital,,,,,,,,,,,,,
divorced,1280,728,179,161,331,348,133,532,9,774,124,13,4612
married,5253,6687,1071,777,2089,1274,904,2294,41,3670,634,234,24928
single,3875,1825,203,119,501,93,379,1137,824,2287,251,74,11568
unknown,14,14,3,3,3,5,5,6,1,12,5,9,80
All,10422,9254,1456,1060,2924,1720,1421,3969,875,6743,1014,330,41188

In [32]:
hs = 348	
p = hs/S
print(f"  Probability that the Customer is Retired and is divorced  {round(p, 2)}")

  Probability that the Customer is Retired and is divorced  0.01

In [34]:
# Given the Customer has the credit card, find the probability that he/she is married ?
pd.crosstab(df['marital'],df['CreditCard'],margins=True)

CreditCard     no   yes    All
marital
divorced     4136   476   4612
married     22396  2532  24928
single       9948  1620  11568
unknown        68    12     80
All         36548  4640  41188

In [35]:
P_AnB = 2532
P_B = 4640
#PA = Customer is Married
# P(A|B) = P(AnB)/P(B)
print(f"Given the Customer has the credit card, probability that he/she is married is {round(P_AnB/P_B,2)}")

Given the Customer has the credit card, probability that he/she is married is 0.55

In [36]:
# If a customer has a management job, find the probability that he has a housing
pd.crosstab(df['job'],df['housing'],margins=True)

housing           no    yes    All
job
admin.          4636   5786  10422
blue-collar     4304   4950   9254
entrepreneur     641    815   1456
housemaid        491    569   1060
management      1363   1561   2924
retired          784    936   1720
self-employed    641    780   1421
services        1818   2151   3969
student          381    494    875
technician      2980   3763   6743
unemployed       430    584   1014
unknown          153    177    330
All            18622  22566  41188

In [37]:
pB = 2924
pAnB = 1561
print(f"Ifcustomer has a management job, find the probability that he has a housing {round(pAnB/pB,2)} ")

Ifcustomer has a management job, find the probability that he has a housing 0.53

In [39]:
dd = pd.read_csv('kerala_floods 1.csv')
dd.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [40]:
dd.shape

(118, 16)

In [41]:
print("\nMissing values per column:")
print(dd.isnull().sum())

Missing values per column:
SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

In [43]:
dd['july_more500'] = (dd['JUL']>500).astype('int') #if less than 500, it will give one, other than that 0

In [44]:
dd['FLOODS'] = dd['FLOODS'].map({"YES":1,"NO":0})
dd.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS,july_more500
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,1,1
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,1,1
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,1,1
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,1,1
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,0,1

In [45]:
df2 = dd[['YEAR','july_more500','FLOODS']]
df2.head()

   YEAR  july_more500  FLOODS
0  1901             1       1
1  1902             1       1
2  1903             1       1
3  1904             1       1
4  1905             1       0

In [46]:
pd.crosstab(df2['FLOODS'],df2['july_more500'],margins=True)

july_more500   0   1  All
FLOODS
0             19  39   58
1              3  57   60
All           22  96  118

In [47]:
p_A = 96/118
p_A

0.8135593220338984

In [50]:
p__B = 60/118
p__B

0.5084745762711864

In [49]:
p__B_AND_A = 57/118
p__B_AND_A

0.4830508474576271

In [52]:
p_B_given_A = p__B_AND_A/p_A
p_B_given_A

0.59375

In [53]:
p_not_A = 22/118
p_not_A

0.1864406779661017

In [60]:
p__B_given_not_A = 3/22
p__B_given_not_A

0.13636363636363635

In [61]:
p_A_given__B = p_B_given_A*p_A/p__B
p_A_given__B

0.9500000000000002